# Generated by Django 5.2.8 on 2025-11-18 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('duration', models.IntegerField(help_text='Duration in weeks')),
                ('course_image', models.ImageField(upload_to='images/course_image/')),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('expertise', models.CharField(choices=[('Python', 'Python'), ('Django', 'Django'), ('Data Science', 'Data Science')], default='Python')),
                ('trainer_photo', models.ImageField(upload_to='images/trainer_photo/')),
            ],
        ),
    ]
